<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Rahuls-MacBook-Pro.local" failures="0" tests="9" name="com.tests.SanityCreateAccount" time="-1714119040.000" errors="1" timestamp="2024-04-26T13:40:20 IST" skipped="0">
  <testcase classname="com.tests.SanityCreateAccount" name="FailTestScreenShot" time="-1714119040.000">
    <error message="
Can inject only one of &lt;ITestContext, XmlTest&gt; into a @AfterTest annotated FailTestScreenShot.
For more information on native dependency injection please refer to https://testng.org/doc/documentation-main.html#native-dependency-injection" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Can inject only one of <ITestContext, XmlTest> into a @AfterTest annotated FailTestScreenShot.
For more information on native dependency injection please refer to https://testng.org/doc/documentation-main.html#native-dependency-injection
at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:445)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:350)
at org.testng.internal.Parameters.createParameters(Parameters.java:702)
at org.testng.internal.Parameters.createConfigurationParameters(Parameters.java:166)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:306)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:661)
at org.testng.TestRunner.afterRun(TestRunner.java:904)
at org.testng.TestRunner.run(TestRunner.java:622)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- FailTestScreenShot -->
  <testcase classname="com.tests.SanityCreateAccount" name="NewAccountCreate" time="2.756"/>
  <testcase classname="com.tests.SanityCreateAccount" name="NameFirst" time="2.806"/>
  <testcase classname="com.tests.SanityCreateAccount" name="DuplicateAccount" time="5.692"/>
  <testcase classname="com.tests.SanityCreateAccount" name="ForgotPassword" time="4.248"/>
  <testcase classname="com.tests.SanityCreateAccount" name="Forgotemail" time="2.676"/>
  <testcase classname="com.tests.SanityCreateAccount" name="Weakpassword" time="2.489"/>
  <testcase classname="com.tests.SanityCreateAccount" name="ExistedNames" time="10.081"/>
  <testcase classname="com.tests.SanityCreateAccount" name="PartialLogout" time="4.204"/>
</testsuite> <!-- com.tests.SanityCreateAccount -->
